global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'nestjs_microsservicos'
    static_configs:
      - targets: 
        - 'ms-medicos:3001'
        - 'ms-pacientes:3002'
        - 'ms-atendimentos:3003'
        - 'ms-auditoria:3004'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']